name: Integration


on:

  schedule:
    - cron: "*/20 * * * *"

  push:
    branches: ["main"]

  pull_request: 
    branches: ["main"]

  
jobs:
  Integrate:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: install requests, beautifulsoup
        run: pip install requests bs4
      - name: launch the meteo_scrapper
        run: python main.py
      - name: getContent of meteo.txt
        run: cat meteo.txt
      - name: try push meteo.txt: correction
        run: 
          git add .
      - name: step 1
        run: git commit -m "step 1"
      - name: step 2
        run: git push -u origin main

